enum EBOOK {
  CREATE_BOOK = 'CREATE_BOOK',
  DELETE_BOOK = 'DELETE_BOOK',
  GET_BOOKS = 'GET_BOOKS',
  GET_BOOK = 'GET_BOOK',
  UPDATE_BOOK_HISTORY = 'UPDATE_BOOK_HISTORY',
}

enum ESTORE {
  FONT_SIZE = 'FONT_SIZE',
  LINE_HEIGHT = 'LINE_HEIGHT',
  LETTER_SPACING = 'LETTER_SPACING',
  FONT_WEIGHT = 'FONT_WEIGHT',

  FONT_COLOR = 'FONT_COLOR',
  BACKGROUND_COLOR = 'BACKGROUND_COLOR',
  TITLE_COLOR = 'TITLE_COLOR',
  PROGRESS_COLOR = 'PROGRESS_COLOR',
}

enum EIPC {
  ROUTE = 'ROUTE',

  // book
  CREATE_BOOK = EBOOK.CREATE_BOOK,
  DELETE_BOOK = EBOOK.DELETE_BOOK,
  GET_BOOKS = EBOOK.GET_BOOKS,
  GET_BOOK = EBOOK.GET_BOOK,
  UPDATE_BOOK_HISTORY = EBOOK.UPDATE_BOOK_HISTORY,

  // store
  GET_STORE = 'GET_STORE',
  SET_STORE = 'SET_STORE',
  INCRECE_STORE = 'INCRECE_STORE',
  DECRECE_STORE = 'DECRECE_STORE',
  RESET_STORE = 'RESET_STORE',
}

enum EROUTE {
  ROOT = 'Root',
  HOME = 'Home',
  READ = 'Read',
  SEARCH = 'Search',
}

export { EBOOK, ESTORE, EIPC, EROUTE }
